# Generated by Django 5.1 on 2026-04-15 13:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spatial_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(help_text='Hotspot intensity score')),
                ('dispute_count', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-intensity'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_area', models.FloatField(blank=True, help_text='Overlap area in hectares', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('PENDING', 'Pending')], default='OPEN', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Overlap geometry', null=True, srid=4326)),
                ('farm_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='spatial_data.farmparcel')),
                ('mine_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='spatial_data.mineclaim')),
            ],
            options={
                'ordering': ['-detected_at'],
                'unique_together': {('mine_claim', 'farm_parcel')},
            },
        ),
    ]
