# Generated by Django 5.1 on 2026-04-15 13:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('boundary_type', models.CharField(choices=[('DISTRICT', 'District'), ('PROVINCE', 'Province')], max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'boundaries',
                'ordering': ['boundary_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('contact_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MineClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_code', models.CharField(max_length=100, unique=True)),
                ('area', models.FloatField(help_text='Area in hectares')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPUTED', 'Disputed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_claims', to='spatial_data.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_code', models.CharField(max_length=100, unique=True)),
                ('land_use', models.CharField(blank=True, max_length=100)),
                ('area', models.FloatField(blank=True, help_text='Area in hectares', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_parcels', to='spatial_data.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
